services:
  app:
    build:
      context: .
      dockerfile: .dockerfile
    container_name: rmq_php
    volumes:
      - ./php:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - ecommerce
    command: tail -f /dev/null

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq-ex01
    ports:
      - "5672:5672"    # AMQP protocol
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce

  mysql:
    image: mysql:8.0
    container_name: rabbitmq-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge
